/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tocsys.Interfaces;

import com.mysql.cj.jdbc.CallableStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import tocsys.ConexionBD;
import java.sql.*;
import java.sql.Types;          // Para LONGNVARCHAR, VARCHAR, etc.

/**
 *
 * @author Jesus
 */
public class RegistrarServicio extends javax.swing.JFrame {
    String busqueda = "";
    
    
    
    public void registroServicio(String p_nombre, String p_descripcion, String p_duracion){
        String sql = "{call AgregarServicio(?, ?, ?, 1)}";
        
    
        try (
                java.sql.Connection conn = ConexionBD.obtenerConexion();
                CallableStatement stmt = (CallableStatement) conn.prepareCall(sql)) {
            stmt.setString(1, p_nombre);        // Primer parámetro (String)
            stmt.setString(2, p_descripcion);   // Segundo parámetro (String)
            stmt.setString(3, p_duracion);         // Tercer parámetro (int)

            
            // 2. Ejecutar el procedimiento
            boolean tieneResultados = stmt.execute();
            String mensaje = "No se pudo agregar el servicio, error en el sistema";
            // 3. Procesar el mensaje de retorno (SELECT)
            if (tieneResultados) {
                try (ResultSet rs = stmt.getResultSet()) {
                    if (rs.next()) {
                        mensaje = rs.getString("mensaje");
                        System.out.println("Resultado: " + mensaje);
                    }
                }
            }
            JOptionPane.showMessageDialog(this, mensaje);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    
    public void actualizarServicio(String p_nomServicio,String p_nombre, String p_descripcion, String p_duracion){
        String sql = "{call ActualizarServicio(?,?, ?, ?, 1, ?)}";
        
    
        try (
                java.sql.Connection conn = ConexionBD.obtenerConexion();
                CallableStatement stmt = (CallableStatement) conn.prepareCall(sql)) {
            stmt.setString(1, p_nomServicio);        // Primer parámetro (String)
            stmt.setString(2, p_nombre);        // Primer parámetro (String)
            stmt.setString(3, p_descripcion);   // Segundo parámetro (String)
            stmt.setString(4, p_duracion);         // Tercer parámetro (int)
            stmt.registerOutParameter(p_nombre,Types.LONGNVARCHAR ); // Quinto parámetro (OUT)

            stmt.execute();
            String resultado = stmt.getString(5); // Leer parámetro OUT

            JOptionPane.showMessageDialog(this, resultado);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    

    public String getBusqueda() {
        return busqueda;
    }

    public void setBusqueda(String busqueda) {
        this.busqueda = busqueda;
    }
    
    
    /**
     * Creates new form AgregarServicio
     */
    public RegistrarServicio() {
        initComponents();
        // esto recibe si va a registrar o actualziar, para usar la misma interfaz
            lblTitulo.setText("REGISTRAR SERVICIO");
    }
    
    
    public RegistrarServicio(String servBuscado) {
        initComponents();
        busqueda = servBuscado;
            //va a actualizazr los datos, cambiar el lbl 
            lblTitulo.setText("ACTUALIZAR SERVICIO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbHoras = new javax.swing.JComboBox<>();
        jcbMinutos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(989, 369));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblTitulo.setText("REGISTRAR SERVICIO");

        jLabel1.setText("NOMBRE");

        jLabel2.setText("DESCRIPCION");

        jLabel3.setText("DURACIÓN");

        jcbHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05" }));

        jcbMinutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "10", "20", "30", "40", "50" }));

        jLabel4.setText("Horas");

        jLabel6.setText("Minutos");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jcbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addGap(138, 138, 138)
                                    .addComponent(btnAceptar))
                                .addComponent(txtDesc)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNom))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(btnAceptar)
                        .addComponent(jcbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String nombre, descripcion, duracion;
        
        nombre = txtNom.getText();
        descripcion = txtDesc.getText();
        
        if(nombre.isBlank() || nombre.isEmpty() || descripcion.isBlank() || descripcion.isEmpty()){
            JOptionPane.showMessageDialog(this, "NO PUEDE DEJAR CAMPOS VACIOS");
            return;
        }
        
        //validacion de la longitud de los campos
        if(nombre.length()>30){
            JOptionPane.showMessageDialog(this, "EL NOMBRE SOLO PUEDE TENER 30 CARACTERES");
            return;
        }
        
        if(descripcion.length()>200){
            JOptionPane.showMessageDialog(this, "DESCRIPCIÓN MUY LARGA, SOLO PUEDE TENER 200 CARACTERES");
            return;
        }
        
        String minutos = jcbMinutos.getSelectedItem().toString();
        String horas = jcbHoras.getSelectedItem().toString();
        duracion = horas+":"+minutos+":00";
        
        if(duracion.equals("00:00:00")){
            JOptionPane.showMessageDialog(this, "SELECCIONE UNA DURACIÓN VÁLIDA");
            return;
        }
        
        if(!busqueda.isEmpty()){
        actualizarServicio(busqueda, nombre, descripcion, duracion);
        return;
        }
        //llamo al método para registrar, en caso de que no se esté buscando algo
        registroServicio(nombre, descripcion, duracion);

    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarServicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jcbHoras;
    private javax.swing.JComboBox<String> jcbMinutos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
